"use client";
import { FormEvent, useEffect, useState } from "react";

type Auth = { accessToken: string; email: string };
type Player = { playerTag:string; playerName:string; townHallLevel:number; experienceLevel:number; trophies:number; lastRefreshedAt:string; heroes:{name:string;level:number}[] };
type Recommendation = { type:string; priority:string; reasonCodes:string[]; explanation:string; ruleVersion:string };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080/api/v1";
async function request<T>(path:string, method="GET", body?:unknown, token?:string):Promise<T>{ const response=await fetch(`${apiUrl}${path}`,{method,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined}); if(!response.ok){const error=await response.json().catch(()=>null);throw new Error(error?.message??"Request failed");} return response.json() as Promise<T>; }
export default function Home(){ const [auth,setAuth]=useState<Auth|null>(null); const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [tag,setTag]=useState("");const [player,setPlayer]=useState<Player|null>(null);const [recommendation,setRecommendation]=useState<Recommendation|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("clash-coach-auth");if(saved)setAuth(JSON.parse(saved));},[]);
 useEffect(()=>{if(auth)loadProfile(auth.accessToken);},[auth]);
 async function loadProfile(token:string){try{const p=await request<Player>("/players/me","GET",undefined,token);setPlayer(p);setRecommendation(await request<Recommendation>("/players/me/recommendation","GET",undefined,token));}catch{setPlayer(null);setRecommendation(null);}}
 async function submitAuth(event:FormEvent<HTMLFormElement>,path:string){event.preventDefault();setBusy(true);setError("");try{const result=await request<Auth>(path,"POST",{email,password});localStorage.setItem("clash-coach-auth",JSON.stringify(result));setAuth(result);}catch(e){setError(e instanceof Error?e.message:"Unable to sign in");}finally{setBusy(false);}}
 async function linkOrRefresh(refresh=false){if(!auth)return;setBusy(true);setError("");try{const p=await request<Player>(refresh?"/players/me/refresh":"/players/me",refresh?"POST":"PUT",refresh?undefined:{playerTag:tag.trim().toUpperCase()},auth.accessToken);setPlayer(p);setRecommendation(await request<Recommendation>("/players/me/recommendation","GET",undefined,auth.accessToken));}catch(e){setError(e instanceof Error?e.message:"Unable to update player");}finally{setBusy(false);}}
 if(!auth)return <main><section className="panel"><p className="eyebrow">CLASH COACH AI</p><h1>Make every upgrade count.</h1><p className="muted">Link your base to receive deterministic, explainable progression advice.</p><form onSubmit={e=>submitAuth(e,"/auth/login")}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required minLength={12} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>Sign in</button><button type="button" className="secondary" disabled={busy} onClick={()=>{const form=document.querySelector("form");if(form)form.requestSubmit();}}>New here? Register below</button></form><button className="link" disabled={busy} onClick={()=>submitAuth({preventDefault(){}} as FormEvent<HTMLFormElement>,"/auth/register")}>Create account</button>{error&&<p role="alert" className="error">{error}</p>}</section></main>;
 return <main><header><div><p className="eyebrow">CLASH COACH AI</p><h1>Command center</h1></div><button className="secondary" onClick={()=>{localStorage.removeItem("clash-coach-auth");setAuth(null);}}>Sign out</button></header>{error&&<p role="alert" className="error">{error}</p>}{!player?<section className="panel"><h2>Link your player</h2><p className="muted">Enter your public Clash player tag. We never request game credentials.</p><label>Player tag<input placeholder="#ABC123" value={tag} onChange={e=>setTag(e.target.value)}/></label><button disabled={busy||!tag} onClick={()=>linkOrRefresh()}>Link player</button></section>:<><section className="grid"><article className="panel"><p className="eyebrow">{player.playerTag}</p><h2>{player.playerName}</h2><dl><div><dt>Town Hall</dt><dd>{player.townHallLevel}</dd></div><div><dt>Trophies</dt><dd>{player.trophies}</dd></div><div><dt>XP level</dt><dd>{player.experienceLevel}</dd></div></dl><button disabled={busy} onClick={()=>linkOrRefresh(true)}>Refresh profile</button></article><article className="panel recommendation"><p className="eyebrow">{recommendation?.priority??"INFO"} PRIORITY</p><h2>Next focus</h2><p>{recommendation?.explanation??"Calculating advice..."}</p><small>Rule: {recommendation?.ruleVersion}</small></article></section><section className="panel"><h2>Heroes</h2><div className="heroes">{player.heroes.map(hero=><div key={hero.name}><span>{hero.name}</span><strong>Level {hero.level}</strong></div>)}</div><p className="muted">Last refreshed {new Date(player.lastRefreshedAt).toLocaleString()}.</p></section></>}</main>; }
