package com.clashcoach.player;
import com.clashcoach.recommendation.Recommendation; import java.time.Instant; import java.util.*; import java.util.stream.Collectors; import javax.validation.constraints.*;
/** HTTP DTOs for player endpoints. */
public final class PlayerDtos { private PlayerDtos() { }
 public static class LinkRequest { @NotBlank @Pattern(regexp="^#[0289PYLQGRJCUV]{3,15}$",message="must be a valid Clash player tag") private String playerTag; public String getPlayerTag(){return playerTag;} public void setPlayerTag(String playerTag){this.playerTag=playerTag;} }
 public static final class HeroResponse { private final String name;private final int level; public HeroResponse(String name,int level){this.name=name;this.level=level;}public String getName(){return name;}public int getLevel(){return level;} }
 public static final class PlayerResponse { private final String playerTag,playerName;private final int townHallLevel,experienceLevel,trophies;private final Instant lastRefreshedAt;private final List<HeroResponse> heroes; public PlayerResponse(String tag,String name,int townHall,int experience,int trophies,Instant refreshed,List<HeroResponse> heroes){this.playerTag=tag;this.playerName=name;this.townHallLevel=townHall;this.experienceLevel=experience;this.trophies=trophies;this.lastRefreshedAt=refreshed;this.heroes=heroes;}public String getPlayerTag(){return playerTag;}public String getPlayerName(){return playerName;}public int getTownHallLevel(){return townHallLevel;}public int getExperienceLevel(){return experienceLevel;}public int getTrophies(){return trophies;}public Instant getLastRefreshedAt(){return lastRefreshedAt;}public List<HeroResponse> getHeroes(){return heroes;} }
 public static final class RecommendationResponse { private final String type,priority,explanation,ruleVersion;private final List<String> reasonCodes;public RecommendationResponse(String type,String priority,List<String> codes,String explanation,String version){this.type=type;this.priority=priority;this.reasonCodes=codes;this.explanation=explanation;this.ruleVersion=version;}public String getType(){return type;}public String getPriority(){return priority;}public List<String> getReasonCodes(){return reasonCodes;}public String getExplanation(){return explanation;}public String getRuleVersion(){return ruleVersion;} }
 public static PlayerResponse player(Player player,PlayerSnapshot snapshot,List<PlayerData.Hero> heroes){return new PlayerResponse(player.getPlayerTag(),player.getPlayerName(),player.getTownHallLevel(),snapshot.getExperienceLevel(),snapshot.getTrophies(),snapshot.getCapturedAt(),heroes.stream().map(h->new HeroResponse(h.getName(),h.getLevel())).collect(Collectors.toList()));} public static RecommendationResponse recommendation(Recommendation recommendation,List<String> codes){return new RecommendationResponse(recommendation.getType(),recommendation.getPriority(),codes,recommendation.getExplanation(),recommendation.getRuleVersion());}
}
